name: "Sprint 3 – Unified Mapping & Controller Integration"
description: "Implement unified mapping validator, auto-generation, and controller integration."
title: "Sprint 3 – Unified Mapping & Controller Integration"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Sprint 3 – Unified Mapping & Controller Integration

        Ziel dieses Sprints:  
        Vereinheitlichte Mappings (JSON+YAML), automatische Ableitung von Controller-Slots, 
        Validierung, Hot-Reload und Dokumentation.

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Was wird in diesem Sprint umgesetzt?
      value: |
        - Unified mapping loader for YAML+JSON
        - Mapping validator with conflict detection
        - Controller integration (auto-slot-assignment)
        - Hot-reload logic for interactive changes
        - Docs + mappings for EQ+, Compressor, Utility
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - Mapping validator detects conflicts and missing ranges
        - Controller mapping is auto-derived from unified format
        - Hot reload performs update < 50ms
        - Examples (EQ+, Compressor, Utility) validated and usable
        - Docs complete and merged to main
    validations:
      required: true
